-- models/staging/stg_dwh__paghe_fatture.sql

select
    {{ dbt_utils.generate_surrogate_key(['Azienda', 'Anno', 'Mese', 'Matricola']) }} as paghe_fatture_id,
    Azienda as azienda,
    Anno as anno,
    Mese as mese,
    Matricola as matricola,
    GGLav as gg_lav,
    GGRetr as gg_retr,
    HHLav as hh_lav,
    HHRetr as hh_retr,
    Stipendio as stipendio,
    RetribTFR as retrib_tfr,
    ImponImps as impon_imps,
    Netto as netto,
    CostoRetr as costo_retr,
    CtrRetr as ctr_retr,
    InailRetr as inail_retr,
    Ratei as ratei,
    CtrRatei as ctr_ratei,
    InailRatei as inail_ratei,
    Tfr as tfr,
    EbiFormRetr as ebi_form_retr,
    EbiFormRatei as ebi_form_ratei,
    RimbSpese as rimb_spese,
    Trasferte as trasferte,
    CtrTrasferte as ctr_trasferte,
    UnaTantum as una_tantum,
    CtrUnaTantum as ctr_una_tantum,
    PremioDecontrib as premio_decontrib,
    CtrDecontrib as ctr_decontrib,
    CtrAuto as ctr_auto,
    Arretrati as arretrati,
    CtrArretrati as ctr_arretrati,
    ArretratiAP as arretrati_ap,
    CtrArrAP as ctr_arr_ap,
    UnaTantumAP as una_tantum_ap,
    CtrTantumAP as ctr_tantum_ap,
    Causale90 as causale_90,
    Causale91 as causale_91,
    CtrCaus9091 as ctr_caus_90_91,
    Causale92 as causale_92,
    CtrCaus9296 as ctr_caus_92_96,
    Causale93 as causale_93,
    Causale94 as causale_94,
    Causale96 as causale_96,
    Causale99 as causale_99,
    Rival_Ratei as rival_ratei,
    Contrib_Riv_Ratei as contrib_riv_ratei,
    Ind_dispon as ind_dispon,

    -- Aggiungio un timestamp per sapere quando il modello è stato processato
    current_timestamp() as dbt_loaded_at

from {{ source('dwh_clean_data', 'paghefatture') }}