-- models/staging/stg_dwh__paghe_fatture.sql

select
    Azienda,
    Anno,
    Mese,
    Matricola,
    GGLav,
    GGRetr,
    HHLav,
    HHRetr,
    Stipendio,
    RetribTFR,
    ImponImps,
    Netto,
    CostoRetr,
    CtrRetr,
    InailRetr,
    Ratei,
    CtrRatei,
    InailRatei,
    Tfr,
    EbiFormRetr,
    EbiFormRatei,
    RimbSpese,
    Trasferte,
    CtrTrasferte,
    UnaTantum,
    CtrUnaTantum,
    PremioDecontrib,
    CtrDecontrib,
    CtrAuto,
    Arretrati,
    CtrArretrati,
    ArretratiAP,
    CtrArrAP,
    UnaTantumAP,
    CtrTantumAP,
    Causale90,
    Causale91,
    CtrCaus9091,
    Causale92,
    CtrCaus9296,
    Causale93,
    Causale94,
    Causale96,
    Causale99,
    Rival_Ratei,
    Contrib_Riv_Ratei,
    Ind_dispon,

    -- Aggiungio un timestamp per sapere quando il modello è stato processato
    current_timestamp() as dbt_loaded_at

from {{ source('dwh_clean_data', 'paghefatture') }}