-- models/staging/stg_paghe_fatture.sql

select
    Azienda as company_name, -- Rinomino
    Anno as year,
    Mese as month,
    Matricola as employee_id,
    GGLav as days_worked,
    GGRetr as days_paid,
    HHLav as hours_worked,
    HHRetr as hours_paid,
    Stipendio as salary_amount,
    RetribTFR as tfr_salary_base,
    ImponImps as taxable_income,
    Netto as net_pay,
    CostoRetr as payroll_cost,
    CtrRetr as payroll_contributions,
    InailRetr as inail_payroll,
    Ratei as accruals_amount,
    CtrRatei as accruals_contributions,
    InailRatei as inail_accruals,
    Tfr as tfr_amount,
    EbiFormRetr as ebi_form_payroll,
    EbiFormRatei as ebi_form_accruals,
    RimbSpese as expense_reimbursements,
    Trasferte as travel_expenses,
    CtrTrasferte as travel_contributions,
    UnaTantum as one_off_payment,
    CtrUnaTantum as one_off_contributions,
    PremioDecontrib as tax_exempt_bonus,
    CtrDecontrib as tax_exempt_contributions,
    CtrAuto as car_contributions,
    Arretrati as arrears_amount,
    CtrArretrati as arrears_contributions,
    ArretratiAP as arrears_ap_amount,
    CtrArrAP as arrears_ap_contributions,
    UnaTantumAP as one_off_ap_amount,
    CtrTantumAP as one_off_ap_contributions,
    Causale90 as causal_90,
    Causale91 as causal_91,
    CtrCaus9091 as contributions_causal_90_91,
    Causale92 as causal_92,
    CtrCaus9296 as contributions_causal_92_96,
    Causale93 as causal_93,
    Causale94 as causal_94,
    Causale96 as causal_96,
    Causale99 as causal_99,
    Rival_Ratei as accruals_revaluation,
    Contrib_Riv_Ratei as accruals_revaluation_contributions,
    Ind_dispon as availability_allowance,

    -- Aggiungio un timestamp per sapere quando il modello è stato processato
    current_timestamp() as dbt_loaded_at

from {{ source('dwh_clean_data', 'paghefatture') }}